name: Roslyn Analysis Workflow

on:
  repository_dispatch:
    types:
      - trigger-roslyn-analysis

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Roslyn repository
        uses: actions/checkout@v2
        with:
          repository: ATI-SWQA/Roslyn
          ref: main
          path: Roslyn
          submodules: 'recursive'

      - name: Download Environment Variables Artifact
        uses: actions/download-artifact@v2
        with:
          name: environment-variables

      - name: Check if Environment Variables File Exists
        run: |
          if [ -f ./env-vars.txt ]; then
            echo "Environment variables file exists."
          else
            echo "Environment variables file does not exist."
            exit 1  # 파일이 없으면 오류로 처리
          fi

      - name: Restore dependencies
        run: dotnet restore Roslyn/RoslynCode/Roslyn.csproj

      - name: Set Environment Variables from File
        run: |
          # 다운로드한 파일에서 환경변수를 읽어옵니다.
          source ./env-vars.txt
          export PROJECT_PATH
          export CHANGED_FILES
          export OTHER_VARIABLE

      - name: Analyze and Create Report File
        run: |
          timestamp=$(TZ="Asia/Seoul" date +"%Y%m%d%H%M")
          reportFolderPath="report" 
          reportFilePath="$reportFolderPath/coding_rule_violation_${timestamp}.txt"  
          mkdir -p "$reportFolderPath"  
          echo "Creating report file: $reportFilePath"
          echo "" > $reportFilePath
          echo "::set-output name=reportFilePath::$reportFilePath"
          echo "REPORT_FILE_PATH=$reportFilePath" >> $GITHUB_ENV
        id: create_report

      - name: Build and Run Roslyn Analysis
        run: |
          REPORT_FILE_PATH="${REPORT_FILE_PATH// /}"
          dotnet run --project Roslyn/RoslynCode/Roslyn.csproj >> $REPORT_FILE_PATH
        env:
          CHANGED_FILES: ${{env.CHANGED_FILES}}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}

      - name: Commit and Push Report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
        run: |
          branch="${{ github.ref }}"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Add coding standard report"
            git diff-index --quiet HEAD -- ':!roslyn_report.txt' || git commit -m "Add coding standard report"
            git push origin "$branch"
          else
            echo "No changes to commit."
          fi
